services:
  app:
    build:
      context: . 
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-80}:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      PGPASSWORD: "${DB_PASSWORD:-secret}"
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
    tty: true
    ports:
      - "5499:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
