version: '3.8'

services:
  app:
    image: php:7.4-fpm
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"  # Expondo a porta 8000 do container para a porta 8000 do host
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: laravel_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5499:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
